apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/argoproj/argo-cd.git'
              revision: HEAD
              directories:
                - path: applicationset/examples/matrix/cluster-addons/*
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-{{server}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/argoproj-labs/applicationset.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: matrix
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

